/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.sarm.angbe;

import io.swagger.model.IntegrationTestResult;
import io.swagger.annotations.*;
import io.swagger.model.ToDoResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-04-19T17:35:38.768Z")

@Api(value = "integrationTest", description = "the integrationTest API")
public interface IntegrationTestApi {

    IntegrationTestApiDelegate getDelegate();

    @ApiOperation(value = "Run integration tests against remote API", nickname = "integrationTestGet", notes = "", response = IntegrationTestResult.class, tags={ "test", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = IntegrationTestResult.class) })
    @RequestMapping(value = "/integrationTest",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<? extends ToDoResponse> integrationTestGet(@NotNull @ApiParam(value = "base url of remote API to test", required = true) @Valid @RequestParam(value = "url", required = true) String url, HttpServletRequest request) {
        getDelegate().setRequest(request);
        return getDelegate().integrationTestGet(url);
    }

}
